sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - cp .env.travis .env
  - cp backend/.env.travis backend/.env

install:
  - sudo docker-compose up -d --build workspace database
  - sudo docker-compose exec -T workspace composer install --no-interaction --prefer-dist --optimize-autoloader
  - sudo docker-compose exec -T workspace php artisan key:generate
  - sudo docker-compose exec -T workspace php artisan migrate
  - sudo docker-compose exec -T workspace php artisan db:seed

script:
  - sudo docker-compose exec -T workspace vendor/bin/phpunit