language: php

sudo: required

services:
  - docker

php:
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - cp backend/.env.travis backend/.env
  - docker-compose up -d workspace database
  - docker-compose exec workspace composer install --no-interaction --prefer-dist --optimize-autoloader
  - docker-compose exec workspace php artisan key:generate

script:
  - docker-compose exec workspace phpunit

matrix:
  allow_failures:
    - php: 7.1