language: php

sudo: required

services:
  - docker
  - mysql

php:
  - 7.0
  - 7.1

mysql:
  database: homestead_test
  username: root
  encoding: utf8

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - cp backend/.env.travis backend/.env
  - docker-compose up -d workspace
  - docker-compose exec -T workspace composer install --no-interaction --prefer-dist --optimize-autoloader
  - docker-compose exec -T workspace php artisan key:generate
  - docker-compose exec -T workspace php artisan migrate
  - docker-compose exec -T workspace php artisan db:seed

script:
  - docker-compose exec -T workspace vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7.1