version: '2'
services:
    web:
#        restart: always
        build:
            context: ./web
        volumes:
            - ./app:/var/www
        ports:
            - "8080:80"
            - "443:443"
        links:
            - app
    app:
        build:
            context: ./app
        volumes:
            - ./app:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=finance"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=secret"
    database:
        volumes:
            - ./database:/var/lib/mysql:rw
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=finance"
        ports:
            - "33061:3306"